## 통계학 실험 3장 과제

#### 1. 1부터 100 사이에서 40개의 서로 다른 정수를 임의로 선택하여 저장하자.

In [1]:
import numpy as np

numbers = 1 + np.random.choice(100, size=40, replace=False)
print(numbers)

[55 41 23 45 81 20 33  1 66 73 77 32 91 10 84 57  5 19 47  3 37 95 44 29
 94  7 46 11 99 50 60 13 21  9 68 42 96 78 72 85]


1-1) 만들어진 벡터를 사용하여 5행 8열의 행렬을 생성하시오.

In [2]:
matrix = numbers.reshape(5, 8)
print(matrix)

[[55 41 23 45 81 20 33  1]
 [66 73 77 32 91 10 84 57]
 [ 5 19 47  3 37 95 44 29]
 [94  7 46 11 99 50 60 13]
 [21  9 68 42 96 78 72 85]]


1-2) 예제 1에서 생성된 행렬에서 2행과 3행만을 추출하여 저장하시오.

In [3]:
two_rows = matrix[1:3]
print(two_rows)

[[66 73 77 32 91 10 84 57]
 [ 5 19 47  3 37 95 44 29]]


1-3) 예제 1에서 생성된 행렬에서 (1,4,7,8)열을 추출하여 저장하시오.

In [4]:
selected_columns = matrix[:, [0, 3, 6, 7]]
print(selected_columns)

[[55 45 33  1]
 [66 32 84 57]
 [ 5  3 44 29]
 [94 11 60 13]
 [21 42 72 85]]


1-4) 예제 1에서 생성된 행렬의 7번째 열의 평균과 분산을 구하시오.

In [5]:
col = matrix[:, 6]
print(f'''
7번째 열 : {col}
평균     : {col.mean()}
분산     : {col.var()}
''')


7번째 열 : [33 84 44 60 72]
평균     : 58.6
분산     : 339.04



#### 2. 1부터 20 사이에서 1개의 숫자를 임의로 선택하여 저장하자. 이 숫자가 10 이상이면 “P”를 출력하고 10 미만이면 “NP”를 출력하는 코드를 작성해보시오.

In [6]:
num = np.random.randint(1, 21)
print('P' if num >= 10 else 'NP')

P


#### 3. 1부터 20 사이에서 8개의 숫자를 임의로 선택하여 저장하자. 8개의 숫자들 각각에 대해 숫자가 10 이상이면 “P”를 출력하고 10 미만이면 “NP”를 출력하는 코드를 작성해보시 오.

In [7]:
nums = 1 + np.random.choice(20, size=8, replace=False)
for num in nums:
    print('P' if num >= 10 else 'NP')

NP
P
NP
P
P
NP
P
P


#### 4. for문을 이용하여 다음을 출력하는 코드를 작성하시오.

"number 1 is odd"

"number 4 is even"

"number 7 is odd"

...

"number 58 is even"

In [8]:
for n in range(1, 59, 3):
    print(f'"number {n} is ' + ('odd"' if n % 2 == 1 else 'even"'))

"number 1 is odd"
"number 4 is even"
"number 7 is odd"
"number 10 is even"
"number 13 is odd"
"number 16 is even"
"number 19 is odd"
"number 22 is even"
"number 25 is odd"
"number 28 is even"
"number 31 is odd"
"number 34 is even"
"number 37 is odd"
"number 40 is even"
"number 43 is odd"
"number 46 is even"
"number 49 is odd"
"number 52 is even"
"number 55 is odd"
"number 58 is even"



#### 5. 다음을 생성하시오.

5-1) 1부터 136까지 5의 간격으로 array 생성

5-2) 1부터 136까지 길이 20인 array 생성

(Hint for 1 and 2 : numpy.linspace 또는 numpy.arange 이용)

5-3) 두 벡터의 길이를 비교하시오.



In [9]:
a = np.arange(1, 137, 5)
b = np.linspace(1, 136, 20)

print(f'''
5-1: a = {a}

5-2: b = {b}

len(a) = {len(a)} > len(b) = {len(b)}
''')


5-1: a = [  1   6  11  16  21  26  31  36  41  46  51  56  61  66  71  76  81  86
  91  96 101 106 111 116 121 126 131 136]

5-2: b = [  1.           8.10526316  15.21052632  22.31578947  29.42105263
  36.52631579  43.63157895  50.73684211  57.84210526  64.94736842
  72.05263158  79.15789474  86.26315789  93.36842105 100.47368421
 107.57894737 114.68421053 121.78947368 128.89473684 136.        ]

len(a) = 28 > len(b) = 20



#### 6. "cdc.txt" 자료를 읽어오자.

In [10]:
import pandas as pd

data = pd.read_csv('cdc.txt', sep=' ')

**6-1. 다음을 출력하시오. (np.iloc를 사용할 것)**  
1) 20부터 25번째 사람의 키(height)와 몸무게(weight)  
2) 20부터 25번째 사람의 나이(age)

In [11]:
display(data.iloc[19:24, 4:6])

display(data.iloc[19:24, -2:-1])

height  weight
20      67     125
21      69     200
22      65     160
23      73     160
24      67     165

age
20   33
21   48
22   54
23   43
24   30

**6-2. 여자와 남자 각각의 키의 평균을 구하시오.**

In [12]:
print(f'''
여성 평균 신장: {data[data.gender == 'f'].height.mean()}
남성 평균 신장: {data[data.gender == 'm'].height.mean()}
''')


여성 평균 신장: 64.36774997603298
남성 평균 신장: 70.25164594001463



**6-3. 남자이면서 평균 나이 이상인 집단의 몸무게와 여자 이면서 평균 나이 이상인 집단의 몸무게의 평균과 분산을 구하시오.**

In [13]:
old_people_indices = data.age > data.age.mean()

old_male_weight = data[(data.gender == 'm') & old_people_indices].weight
old_female_weight = data[(data.gender == 'f') & old_people_indices].weight

print(f'''
남자이면서 평균 나이 이상인 집단의 몸무게의
  평균: {old_male_weight.mean()}
  분산: {old_male_weight.var()}
  
여자이면서 평균 나이 이상인 집단의 몸무게의
  평균: {old_female_weight.mean()}
  분산: {old_female_weight.var()}
''')


남자이면서 평균 나이 이상인 집단의 몸무게의
  평균: 190.15840118430793
  분산: 1268.992178292121
  
여자이면서 평균 나이 이상인 집단의 몸무게의
  평균: 153.73747368421053
  분산: 1071.1071024814087

