Numpy 연습
========

In [1]:
import numpy as np

# Numpy basics
x = np.array([1, 2, 3])
y = np.array([2, 4, 6])
z = np.array([0.1, 0.2, 0.3, 0.4])

print(type(x))
print(x.dtype)
print(x)

<class 'numpy.ndarray'>
int64
[1 2 3]


In [2]:
# Element-wise arithmetic
print(x + y)
print(x * y)
print(x / y)
try:
    print(x + z)
except ValueError as e:
    print(e)

[3 6 9]
[ 2  8 18]
[ 0.5  0.5  0.5]
operands could not be broadcast together with shapes (3,) (4,) 


In [3]:
# Scalar arithmetic
print(2 * x)
print(y * 2)
print(x / 2)
print(x + 2)
print(x % 2 == 0)

[2 4 6]
[ 4  8 12]
[ 0.5  1.   1.5]
[3 4 5]
[False  True False]


In [4]:
# Multi-dimensional
A = np.array([
    [1, 2],
    [3, 4],
])
B = np.array([
    [5, 6],
    [7, 8],
])
print(A)
print(A * B)
print(A.shape)
print(A.dtype)

[[1 2]
 [3 4]]
[[ 5 12]
 [21 32]]
(2, 2)
int64


In [5]:
# Broadcast
A = np.array([
    [1, 2],
    [3, 4],
])
B = np.array([10, 100])
print(A*B)

[[ 10 200]
 [ 30 400]]


In [6]:
# Access
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
    [10, 11, 12],
])
B = A.flatten()
print(A)
print(B)
print(A[0])
print(A[0][0])
print(A[0, 0])
print('-'.join([str(row) for row in A]))
print(B[[0, 2, 4]])
print(B[np.array([0, 2, 4])])

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
[1 2 3]
1
1
[1 2 3]-[4 5 6]-[7 8 9]-[10 11 12]
[1 3 5]
[1 3 5]


In [7]:
# Trick
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])
print(a)
print(a > 10)
print(a[a > 10])
print(a[2:10])
print(a[2:10:2])
print(a[10:2:-1])
print(a[10:])
print(a[10::-1])
print(a[:10])
print(a[:10:-1])

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[False False False False False False False False False False  True  True
  True  True  True  True  True  True  True]
[11 12 13 14 15 16 17 18 19]
[ 3  4  5  6  7  8  9 10]
[3 5 7 9]
[11 10  9  8  7  6  5  4]
[11 12 13 14 15 16 17 18 19]
[11 10  9  8  7  6  5  4  3  2  1]
[ 1  2  3  4  5  6  7  8  9 10]
[19 18 17 16 15 14 13 12]


In [8]:
# Column
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
    [10, 11, 12],
])
print(A)
print(A.transpose())
print(A[0])
print(A[...,0])
print(A[...,1])
print(A[...,2])

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]]
[1 2 3]
[ 1  4  7 10]
[ 2  5  8 11]
[ 3  6  9 12]
