`@` 연산자
--------

[PEP 465](https://www.python.org/dev/peps/pep-0465/)의 통과로 Python 3.5부터 새로이 생겨난 중위연산자.

In [4]:
import numpy as np

a = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
])
b = np.array([
    [3, 2, 1], 
    [4, 3, 2], 
    [5, 4, 3],
])
c = np.array([
    [3, 1, 2],
    [4, 2, 3],
    [5, 3, 4],
])
d = np.array([
    [1, 3, 2],
    [2, 4, 3],
    [5, 1, 1],
])

# 위아래가 동치
print(np.dot(np.dot(np.dot(a, b), c), d))
print()
print(a @ b @ c @ d)

[[1284 1284  948]
 [3003 3003 2217]
 [4722 4722 3486]]

[[1284 1284  948]
 [3003 3003 2217]
 [4722 4722 3486]]


###### References

- [What’s New In Python 3.5](https://docs.python.org/3/whatsnew/3.5.html#whatsnew-pep-465)
- [PEP 465](https://www.python.org/dev/peps/pep-0465/)